[package]
authors = ["Prasanna V. Loganathar <pvl@prasannavl.com>"]
name = "main"
version = "0.1.0"
[dependencies]
kernel32-sys = "0.2.2"
user32-sys = "0.2.0"
winapi = "0.2.8"
[profile.release]
lto = true